XDG_CONFIG_HOME=/home/nekraut/.config
XDG_DATA_HOME=/home/nekraut/.local/share
XDG_CACHE_HOME=/home/nekraut/.cache
XDG_STATE_HOME=/home/nekraut/.local/state

# REQUIRED: exposed native and Flatpak apps the same way KDE did
XDG_DATA_DIRS=/home/nekraut/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
